---
- hosts: all
  become: true
  vars:
    foreman_installer_options:
      - "--foreman-initial-admin-password {{ foreman_installer_admin_password }}"
      - "--enable-foreman-cli-discovery"
      - "--enable-foreman-cli-openscap"
      - "--enable-foreman-cli-remote-execution"
      - "--enable-foreman-cli-tasks"
      - "--enable-foreman-cli-templates"
      - "--enable-foreman-cli-virt-who-configure"
      - "--enable-foreman-plugin-ansible"
      - "--enable-foreman-plugin-bootdisk"
      - "--enable-foreman-plugin-discovery"
      - "--enable-foreman-plugin-hooks"
      - "--enable-foreman-plugin-openscap"
      - "--enable-foreman-plugin-remote-execution"
      - "--enable-foreman-plugin-templates"
      - "--enable-foreman-plugin-virt-who-configure"
      - "--enable-foreman-proxy-plugin-ansible"
      - "--enable-foreman-proxy-plugin-discovery"
      - "--enable-foreman-proxy-plugin-openscap"
      - "--enable-foreman-proxy-plugin-remote-execution-ssh"
      - "--katello-enable-ostree true"
  roles:
    - role: katello
